exports.API_LIST = [
    'QuickGO API',
    'Ontology Lookup Service API',
    'CTD API',
    'OpenTarget API',
    'LitVar API',
    'Human Phenotype Ontology API',
    'UBERON Ontology API',
    'MyDisease.info API',
    'MyVariant.info API',
    'MyGene.info API',
    'SEMMED Disease API',
    'MyChem.info API',
    'SEMMED Anatomy API',
    'SEMMED Gene API',
    'SEMMED Phenotype API',
    'MGIgene2phenotype API',
    'SEMMED Biological Process API',
    'SEMMED Chemical API',
    'DISEASES API',
    'EBIgene2phenotype API',
    'Gene Ontology Biological Process API',
    'Clinical Risk KP API',
    'Gene Ontology Molecular Activity API',
    'Gene Ontology Cellular Component API',
    'BioThings DGIdb API',
    'Text Mining CO-OCCURRENCE API',
    'Text Mining Targeted Association API',
    'Multiomics Wellness KP API',
    'BioLink API',
    'LINCS Data Portal API',
    'Automat IntAct',
    'Automat Cord19 Scibite',
    'Automat Gtopdb',
    'Automat KEGG',
    'Automat Cord19 Scigraph',
    'Automat Uberongraph',
    'Automat Human GOA',
    'Automat HGNC',
    'Automat CTD',
    'Automat HMDB',
    'Automat Hetio',
    'Automat Panther',
    'Automat Pharos',
    'Automat Chembio',
    'Automat Foodb',
];
